#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

properties = manager.GetProperties()

for path in properties["Modems"]:
	modem = dbus.Interface(bus.get_object('org.ofono', path),
							'org.ofono.Modem')

	properties = modem.GetProperties()

	if "org.ofono.DataConnectionManager" not in properties["Interfaces"]:
		continue

	connmgr = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.DataConnectionManager')

	properties = connmgr.GetProperties()

	if (properties["PrimaryContexts"] == []):
		print "No context available"
		sys.exit(1)

	connmgr.SetProperty("Powered", dbus.Boolean(1))

	path = properties["PrimaryContexts"][0]

	context = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.PrimaryDataContext')

	try:
		context.SetProperty("Active", dbus.Boolean(1))
	except dbus.DBusException, e:
		print "Error activating %s: %s" % (path, str(e))
		exit(2)
