#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

path, properties = modems[0]

ussd = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.SupplementaryServices')

properties = ussd.GetProperties()
state = properties["State"]

print "State: %s" % (state)

if state != "idle":
	ussd.Cancel()
