#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

if len(sys.argv) > 2:
	path = sys.argv[1]
	number = sys.argv[2]
else:
	modems = manager.GetModems()
	path, properties = modems[0]
	number = sys.argv[1]

print "Using modem %s" % path

manager = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.cdma.VoiceCallManager')

manager.Dial(number)
