#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	print "[ %s ]" % (path)

	if "org.ofono.cdma.VoiceCallManager" not in properties["Interfaces"]:
		continue

	mgr = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.cdma.VoiceCallManager')

	properties = mgr.GetProperties()

	for key in properties.keys():
		val = str(properties[key])
		print "    %s = %s" % (key, val)
