#!/usr/bin/python

import dbus
import sys

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	if "org.ofono.cdma.ConnectionManager" not in properties["Interfaces"]:
		continue

	cm = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.cdma.ConnectionManager')

	print "Connecting CDMA Packet Data Service on modem %s..." % path

	if len(sys.argv) > 1:
		cm.SetProperty("Username", (sys.argv[1]))
		print "Setting Username to %s" % (sys.argv[1])

	if len(sys.argv) > 2:
		cm.SetProperty("Password", (sys.argv[2]))
		print "Setting Password to %s" % (sys.argv[2])
