#!/usr/bin/python3

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

path = modems[0][0]

if (len(sys.argv) == 2):
	path = sys.argv[1]

manager = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.VoiceCallManager')

mpty = manager.CreateMultiparty()

for path in mpty:
	print(path)
