#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

path, properties = modems[0]

manager = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.VoiceCallManager')

if len(sys.argv) > 2:
    path = manager.Dial(sys.argv[1], sys.argv[2])
else:
    path = manager.Dial(sys.argv[1], "")

print path
