#!/usr/bin/python3

import sys
import dbus

if (len(sys.argv) < 2):
	print("Usage: %s [modem] icon_id" % (sys.argv[0]))
	sys.exit(1)

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()
modem = modems[0][0]

if (len(sys.argv) == 2):
	icon = sys.argv[1]
elif (len(sys.argv) == 3):
	modem = sys.argv[1]
	icon = sys.argv[2]

print("Using modem %s" % modem)

sim = dbus.Interface(bus.get_object('org.ofono', modem),
						'org.ofono.SimManager')
icon = sim.GetIcon(dbus.Byte(int(icon)))
xpm = ""
for byte in icon:
	xpm += str(byte)
f = open("/tmp/icon.xpm", 'w')
f.write(xpm)
f.close()
