#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

properties = manager.GetProperties()

path = properties["Modems"][0]

modem = dbus.Interface(bus.get_object('org.ofono', path),
						'org.ofono.Modem')

modem.SetProperty("Powered", dbus.Boolean(1))
