#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 2:
	path = sys.argv[1]
else:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
			'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]

print("Enabling MMS data for modem %s..." % path)
cm = dbus.Interface(bus.get_object('org.ofono', path),
		'org.ofono.ConnectionManager')

cm.SetProperty("PoweredForMMS", dbus.Boolean(1))
