#!/usr/bin/python

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 2:
	path = sys.argv[1]
else:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	properties = manager.GetProperties()
	path = properties["Modems"][0]

print "Enabling cell broadcast on modem %s..." % path
cbs = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.CbsManager')

cbs.SetProperty("Powered", dbus.Boolean(1))
