#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	print "[ %s ]" % (path)

	if "org.ofono.MessageManager" not in properties["Interfaces"]:
		continue

	connman = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.MessageManager')

	contexts = connman.GetMessages()

	for path, properties in contexts:
		print "    [ %s ]" % (path)

		for key in properties.keys():
			val = str(properties[key])
			print "        %s = %s" % (key, val)

		print
