#!/usr/bin/python

import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	print "[ %s ]" % (path)

	if "org.ofono.VoiceCallManager" not in properties["Interfaces"]:
		continue

	mgr = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.VoiceCallManager')

	calls = mgr.GetCalls()

	for path, properties in calls:
		print "    [ %s ]" % (path)

		for key in properties.keys():
			if key == 'Icon':
				print "        %s = %d" % (key, properties[key])
			else:
				val = str(properties[key])
				print "        %s = %s" % (key, val)
