#!/usr/bin/python3

from gi.repository import GLib

import dbus
import dbus.mainloop.glib

def incoming_message(message, details, path, interface):
	print("%s" % (message))

	for key in details:
		val = details[key]
		print("    %s = %s" % (key, val))

if __name__ == '__main__':
	dbus.mainloop.glib.DBusGMainLoop(set_as_default=True)

	bus = dbus.SystemBus()

	bus.add_signal_receiver(incoming_message,
					bus_name="org.ofono",
					signal_name = "ImmediateMessage",
						path_keyword="path",
						interface_keyword="interface")

	bus.add_signal_receiver(incoming_message,
					bus_name="org.ofono",
					signal_name = "IncomingMessage",
						path_keyword="path",
						interface_keyword="interface")

	mainloop = GLib.MainLoop()
	mainloop.run()
