#!/usr/bin/python

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 5:
	path, puk_type, puk, pin = sys.argv[1:]
elif len(sys.argv) == 4:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
					'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	puk_type, puk, pin = sys.argv[1:]
else:
	print("%s [PATH] puk_type puk pin" % (sys.argv[0]))

print("Reset pin for modem %s..." % path)
simmanager = dbus.Interface(bus.get_object('org.ofono', path),
				'org.ofono.SimManager')

simmanager.ResetPin(puk_type, puk, pin)
