#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()
path = modems[0][0]

manager = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.SmartMessaging')

vcard = file(sys.argv[2]).read()
path = manager.SendBusinessCard(sys.argv[1], vcard)

print path
