#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

properties = manager.GetProperties()

path = properties["Modems"][0]

manager = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.MessageManager')

if len(sys.argv) == 4:
	manager.SetProperty("UseDeliveryReports",
					dbus.Boolean(int(sys.argv[1])))
	manager.SendMessage(sys.argv[1], sys.argv[2])
else:
	manager.SendMessage(sys.argv[1], sys.argv[2])
