#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()
path = modems[0][0]

manager = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.MessageManager')

if len(sys.argv) == 4:
	manager.SetProperty("UseDeliveryReports",
					dbus.Boolean(int(sys.argv[1])))
	path = manager.SendMessage(sys.argv[1], sys.argv[2])
else:
	path = manager.SendMessage(sys.argv[1], sys.argv[2])

print path
