#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	if "org.ofono.ConnectionManager" not in properties["Interfaces"]:
		continue

	connman = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.ConnectionManager')

	if len(sys.argv) > 1:
		allowed = dbus.Boolean(int(sys.argv[1]))
	else:
		allowed = dbus.Boolean(1)

	connman.SetProperty("RoamingAllowed", allowed)

	print("Setting %s to RoamingAllowed=%d" % (path, allowed))
