#!/usr/bin/python

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 3:
	path = sys.argv[1]
	number = sys.argv[2]
elif len(sys.argv) == 2:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	number = sys.argv[1]
else:
	print "%s [PATH] <number>" % (sys.argv[0])
	exit(1)

print "Setting MSISDN for modem %s..." % path
sim = dbus.Interface(bus.get_object('org.ofono', path), 'org.ofono.SimManager')

sim.SetProperty("SubscriberNumbers", [number]);
