#!/usr/bin/python

import sys
import dbus

bus = dbus.SystemBus()

manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')

modems = manager.GetModems()

for path, properties in modems:
	if "org.ofono.Handsfree" not in properties["Interfaces"]:
		continue

	handsfree = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.Handsfree')

	handsfree.SetProperty("DistractedDrivingReduction",\
				dbus.Boolean(int(sys.argv[1])))
