#!/usr/bin/python3

import dbus
import sys

bus = dbus.SystemBus()

if len(sys.argv) == 3:
	path = sys.argv[1]
	topics = sys.argv[2]
elif len(sys.argv) == 2:
	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
						'org.ofono.Manager')
	modems = manager.GetModems()
	path = modems[0][0]
	topics = sys.argv[1]
else:
	print("%s [PATH] topics" % (sys.argv[0]))

print("Setting cell broadcast topics for modem %s..." % path)
cbs = dbus.Interface(bus.get_object('org.ofono', path),
					'org.ofono.CellBroadcast')

cbs.SetProperty("Topics", topics);
