#!/usr/bin/python

import dbus, sys

if __name__ == "__main__":
	bus = dbus.SystemBus()

	if len(sys.argv) == 2:
		path = sys.argv[1]
	else:
		manager = dbus.Interface(bus.get_object('org.ofono', '/'),
				'org.ofono.Manager')
		modems = manager.GetModems()
		path = modems[0][0]

	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
							'org.ofono.Manager')

	modems = manager.GetModems()
	phonebook = dbus.Interface(bus.get_object('org.ofono', path),
				'org.ofono.Phonebook')

	print phonebook.Import(timeout=100)
