#!/usr/bin/python

import dbus

if __name__ == "__main__":
	bus = dbus.SystemBus()

	manager = dbus.Interface(bus.get_object('org.ofono', '/'),
							'org.ofono.Manager')

	modems = manager.GetModems()
	phonebook = dbus.Interface(bus.get_object('org.ofono', modems[0][0]),
				'org.ofono.Phonebook')

	print phonebook.Import(timeout=100)
