#!/bin/sh

DIR="$(dirname "$0")"

if [ -f config.status ]; then
	make maintainer-clean
fi

(cd "$DIR" && ./bootstrap) && \
    "$DIR/configure" --enable-maintainer-mode \
		--enable-debug \
		--prefix=/usr \
		--mandir=/usr/share/man \
		--sysconfdir=/etc \
		--disable-datafiles
