/*
 *
 *  oFono - Open Source Telephony
 *
 *  Copyright (C) 2008-2010  Intel Corporation. All rights reserved.
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License version 2 as
 *  published by the Free Software Foundation.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 */

/*
 * TS 101.220, Section 7.2, Card Application Toolkit assigned templates,
 * These are the same as 3GPP 11.14 Sections 13.1 and 13.2 
 */
enum stk_envelope_type {
	STK_ENVELOPE_TYPE_SMS_PP_DOWNLOAD = 0xD1,
	STK_ENVELOPE_TYPE_CBS_PP_DOWNLOAD = 0xD2,
	STK_ENVELOPE_TYPE_MENU_SELECTION = 0xD3,
	STK_ENVELOPE_TYPE_CALL_CONTROL = 0xD4,
	STK_ENVELOPE_TYPE_MO_SMS_CONTROL = 0xD5,
	STK_ENVELOPE_TYPE_EVENT_DOWNLOAD = 0xD6,
	STK_ENVELOPE_TYPE_TIMER_EXPIRATION = 0xD7,
	STK_ENVELOPE_TYPE_USSD_DOWNLOAD = 0xD9,
};

/* TS 102.223 Section 9.4 */
enum stk_command_type {
	STK_COMMAND_TYPE_REFRESH = 0x01,
	STK_COMMAND_TYPE_POLL_INTERVAL = 0x02,
	STK_COMMAND_TYPE_POLLING_OFF = 0x03,
	STK_COMMAND_TYPE_SETUP_EVENT_LIST = 0x05,
	STK_COMMAND_TYPE_SETUP_CALL = 0x10,
	STK_COMMAND_TYPE_SEND_SS = 0x11,
	STK_COMMAND_TYPE_SEND_USSD = 0x12,
	STK_COMMAND_TYPE_SEND_SMS = 0x13,
	STK_COMMAND_TYPE_SEND_DTMF = 0x14,
	STK_COMMAND_TYPE_LAUNCH_BROWSER = 0x15,
	STK_COMMAND_TYPE_GEOGRAPICAL_LOCATION_REQUEST = 0x16,
	STK_COMMAND_TYPE_PLAY_TONE = 0x20,
	STK_COMMAND_TYPE_DISPLAY_TEXT = 0x21,
	STK_COMMAND_TYPE_GET_INKEY = 0x22,
	STK_COMMAND_TYPE_GET_INPUT = 0x23,
	STK_COMMAND_TYPE_SELECT_ITEM = 0x24,
	STK_COMMAND_TYPE_SETUP_MENU = 0x25,
	STK_COMMAND_TYPE_PROVIDE_LOCAL_INFORMATION = 0x26,
	STK_COMMAND_TYPE_TIMER_MANAGEMENT = 0x27,
	STK_COMMAND_TYPE_SETUP_IDLE_MODE_TEXT = 0x28,
	STK_COMMAND_TYPE_PERFORM_CARD_APDU = 0x30,
	STK_COMMAND_TYPE_POWER_ON_CARD = 0x31,
	STK_COMMAND_TYPE_POWER_OFF_CARD = 0x32,
	STK_COMMAND_TYPE_GET_READER_STATUS = 0x33,
	STK_COMMAND_TYPE_RUN_AT_COMMAND = 0x34,
	STK_COMMAND_TYPE_LANGUAGE_NOTIFICATION = 0x35,
	STK_COMMAND_TYPE_OPEN_CHANNEL = 0x40,
	STK_COMMAND_TYPE_CLOSE_CHANNEL = 0x41,
	STK_COMMAND_TYPE_RECEIVE_DATA = 0x42,
	STK_COMMAND_TYPE_SEND_DATA = 0x43,
	STK_COMMAND_TYPE_GET_CHANNEL_STATUS = 0x44,
	STK_COMMAND_TYPE_SERVICE_SEARCH = 0x45,
	STK_COMMAND_TYPE_GET_SERVICE_INFORMATION = 0x46,
	STK_COMMAND_TYPE_DECLARE_SERVICE = 0x47,
	STK_COMMAND_TYPE_SET_FRAMES = 0x50,
	STK_COMMAND_TYPE_GET_FRAMES_STATUS = 0x51,
	STK_COMMAND_TYPE_RETRIEVE_MMS = 0x60,
	STK_COMMAND_TYPE_SUBMIT_MMS = 0x61,
	STK_COMMAND_TYPE_DISPLAY_MMS = 0x62,
	STK_COMMAND_TYPE_ACTIVATE = 0x70,
	STK_COMMAND_TYPE_END_SESSION = 0x81,
};
